### ISSUE TITLE
Atom feed contains no content

### ISSUE THREAD

**Issue by nint8835** [videah/blog#3]
Started getting errors this morning from my feed reader for your feed being a 404 (I assume due to 10dbe42b1338c4f754fa07da5b80df7f85115b7e). Just went to swap it over to your Atom feed but at least on my end, the contents of the feed are just

```xml
<feed xml:lang="en"/>
```

**Comment by videah** [comment]
Thank you for letting me know! Can you confirm if this is still the case? The feed is populated on my end and since it's statically generated I'm unsure how it could differ 😮

**Comment by nint8835** [comment]
False alarm, should have tried the feed in my feed reader rather than trusting my browser. Not sure exactly what's on the go but intermittently Firefox is flipping between showing the feed as empty vs containing contents, but the network requests are continually returning results so I think it's just something odd happening with Firefox's XML rendering. Swapping my feed reader over to the new feed returns results as expected.
